### ISSUE TITLE
Where to get the API key ?

### ISSUE THREAD

**Issue by InnocentRoot** [realityexpander/Tasky#63]
First, thank you for this project. 

I was compiling this project, and it needs an API key in the `api.properties` file, but I don't know where to get one.

**Comment by realityexpander** [comment]
Unfortunately, the API is currently private

i would need to set up a public server for that to work and would require me to also monitor it which I don’t have time for at the moment. 

You can try it out if you get the app on the app store. 

Sorry I can’t help more

Best,
Chris

**Comment by realityexpander** [comment]
Im going to close this as "wont fix"
